Only import Core-js functions that are necessary
Somewhere in the depths here, a Core-JS feature uses a Set or some other
fancy non-existent object that produces the following error:

  TypeError: Incompatible receiver, Symbol required

Google reveals nothing. By only polyfilling the necessary functions,
this seems to be avoided.